# specify node image
FROM node:8

# create app directory
WORKDIR /usr/src/app

# install app dependencies
COPY package*.json ./

RUN npm install

# bundle app source
COPY . .

ENV NODE_ENV test
ENV HTTP_PORT 5000
ENV UDP_PORT 5001
ENV UDP_TIMEOUT 30

CMD [ "npm", "test" ]
